### ISSUE TITLE
Access token

### ISSUE THREAD

**Issue by beatume78** [daltonrenaldo/youtube-api#4]
Hi,

I am currently trying to access to some Youtube data through you API.
But I am getting the following error : "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."

It is like the API is making call without the oauth credentials.
Can you please detail how/where I should write down the credentials informations (in a specific file or before in my Meteor.methods): 

YoutubeApi.authenticate({
    type: 'key',
    key: 'YOUR_KEY'
});

I have tried in a specific file (where I have my Facebook login credentials) , and in my file containing the Meteor.methods.

Thank you

**Comment by rpierreye** [comment]
The credentials should be on the server side, and loaded on Meteor.startup: 

```javascript
Meteor.startup(function() {
  YoutubeApi.authenticate({
    type: 'key',
    key: 'YOUR_YOUTUBE_API_KEY'
  });
});
```

If the call you were trying to make requires user authentication, you will have to have an access_token:

```javascript
YoutubeApi.authenticate({
    type: "oauth",
    refresh_token: "your refresh token",
    client_id: "your client id",
    client_secret: "your client secret",
    redirect_url: "your refresh url"
});

// or 

YoutubeApi.authenticate({
    type: "oauth",
    token: "your access token"
});
```

let me know what endpoint of the API you were trying to use, and I can assist you further.

**Comment by daltonrenaldo** [comment]
The credentials should be on the server side, and loaded on Meteor.startup: 

``` javascript
Meteor.startup(function() {
  YoutubeApi.authenticate({
    type: 'key',
    key: 'YOUR_YOUTUBE_API_KEY'
  });
});
```

If the call you were trying to make requires user authentication, you will have to have an access_token:

``` javascript
YoutubeApi.authenticate({
    type: "oauth",
    refresh_token: "your refresh token",
    client_id: "your client id",
    client_secret: "your client secret",
    redirect_url: "your refresh url"
});

// or 

YoutubeApi.authenticate({
    type: "oauth",
    token: "your access token"
});
```

let me know what endpoint of the API you were trying to use, and I can assist you further.

**Comment by beatume78** [comment]
Hi,

Thank you for the fast reply.
I will check this later , as I am @work right now.

**Comment by beatume78** [comment]
Hi,

I succeed in making request to the Youtube API.
I am trying to get information from the https://developers.google.com/youtube/v3/docs/search.
The main idea is to get basical information of single videos. I guess I may try other endpoints of the API , and I will try to figure out which one match better with my need.

Meanwhile if you have any tips , advices , feel free to teach me.
I will let you know if I face other difficulties.

Thank you again.

**Comment by beatume78** [comment]
Hi,

I will need some help again , but I guess this more related to meteor ( I am quite a newbie in meteor and JSON object):

The API call returns a [Object Object] , but I cannot get any information on the fields available in this.

searchVideo: function(search) {
        console.log ("appel YT");
        //var YTGetSync = Meteor.wrapAsync(YoutubeApi);
        var result =YoutubeApi.search.list ({
            part: "id,snippet",
            type: "video",
            maxResults: 5,
            //q: search,
            q: 'liKn9h7UhxA',
        }
        , function (err, data) {
            console.log("res appel API :"+data);
            return data;
        });
    }

I have tried to wrap the call , and saving the result into a collection.
But the collection is empty.

Thanks

**Comment by daltonrenaldo** [comment]
try this `console.log("res appel API: ", data, 2);`

**Comment by daltonrenaldo** [comment]
try this 

``` javascript
console.log("res appel API: ", data, 2);
```

**Comment by beatume78** [comment]
Hello,

Have been idle for a while.
Viewing the result in the console logs is OK, but why can't store the result in a var(returning it on client side is another question).

Could you please show me how I can do store the result.
